plugins {
    id 'java-library' // 다른 모듈에서 사용할 라이브러리 모듈임을 명시
}

group = "com.hanumoka.sado"
version = "0.0.1-SNAPSHOT"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

dependencies {
    // 공통으로 사용할 라이브러리
    api 'org.springframework.boot:spring-boot-starter'
    api 'org.projectlombok:lombok'

    annotationProcessor 'org.projectlombok:lombok'

}